# Generated by Django 5.1.6 on 2025-02-26 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('style_number', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('sample_type', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('main_category', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.URLField()),
                ('materials', models.ManyToManyField(related_name='product_materials', to='api.material')),
                ('images', models.ManyToManyField(related_name='product_images', to='api.productimage')),
            ],
        ),
    ]
