# Generated by Django 5.1.6 on 2025-02-26 13:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(upload_to='product_images/'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image_url',
            field=models.FileField(upload_to='product_images/'),
        ),
    ]
