# Generated by Django 5.1.6 on 2025-02-26 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_contactus_options_alter_inquiry_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inquiry',
            options={'verbose_name': 'Inquiry', 'verbose_name_plural': 'Inquiries'},
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='inquiry_items', to='api.inquiryitems'),
        ),
    ]
