# Generated by Django 5.1.6 on 2025-02-26 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_inquiry_options_alter_inquiry_items'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inquiryitems',
            options={'verbose_name': 'Inquiry Item', 'verbose_name_plural': 'Inquiry Items'},
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='items',
        ),
        migrations.AddField(
            model_name='inquiryitems',
            name='inquiry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inquiry_items', to='api.inquiry'),
        ),
    ]
