# Generated by Django 5.1.6 on 2025-02-26 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_inquiryitems_options_remove_inquiry_items_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquiryitems',
            name='inquiry',
        ),
        migrations.AddField(
            model_name='inquiry',
            name='items',
            field=models.ManyToManyField(blank=True, to='api.inquiryitems'),
        ),
    ]
